export const SET_CALCULATED_LAYOUT = "SET_CALCULATED_LAYOUT";
export const ERR_TYPE_SET_CALCULATED_LAYOUT = "SET_CALCULATED_LAYOUT";
export const RESET_STATE = "RESET_STATE";
export const BOOK_FORM = "BOOK_FORM";
